---
# =============================================================================
# ROLE: common
# Basic VPS configuration (system, firewall, directories)
# =============================================================================

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: [common, system]

- name: Upgrade all packages to latest version
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  tags: [common, system]

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - net-tools
      - ufw
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - locales
      - cron
    state: present
  tags: [common, packages]

- name: Set timezone
  community.general.timezone:
    name: "{{ vps_timezone }}"
  tags: [common, system]

- name: Set locale
  community.general.locale_gen:
    name: "{{ vps_locale }}"
    state: present
  tags: [common, system]

- name: Get system memory information
  ansible.builtin.command: free -m
  register: common_memory_info
  changed_when: false
  tags: [common, system]

- name: Parse total RAM in MB
  ansible.builtin.set_fact:
    common_total_ram_mb: >-
      {{ (common_memory_info.stdout | regex_search('Mem:\\s+(\\d+)'))
         .groups[0] | int | default(2048) }}
  tags: [common, system]

- name: Check if swap exists
  ansible.builtin.stat:
    path: /swapfile
  register: common_swap_file
  tags: [common, swap]

- name: Display RAM information
  ansible.builtin.debug:
    msg: |
      System RAM: {{ common_total_ram_mb }} MB ({{ (common_total_ram_mb / 1024) | round(2) }} GB)
      Swap file exists: {{ common_swap_file.stat.exists }}
      Will create swap: {{ not common_swap_file.stat.exists and common_total_ram_mb | int < 2048 }}
  tags: [common, swap]

- name: Create swap file for systems with < 2GB RAM
  when:
    - not common_swap_file.stat.exists
    - common_total_ram_mb | int < 2048
  tags: [common, swap]
  block:
    - name: Allocate swap file (2GB)
      ansible.builtin.command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        mode: "0600"

    - name: Make swap
      ansible.builtin.command: mkswap /swapfile
      when: not common_swap_file.stat.exists
      changed_when: true

    - name: Enable swap
      ansible.builtin.command: swapon /swapfile
      when: not common_swap_file.stat.exists
      changed_when: true

    - name: Add swap to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/swapfile none swap sw 0 0"
        state: present

    - name: Set swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "10"
        state: present

    - name: Log swap creation
      ansible.builtin.debug:
        msg: "✅ Created 2GB swap file (system has {{ common_total_ram_mb }} MB RAM)"

- name: Skip swap creation (sufficient RAM)
  ansible.builtin.debug:
    msg: "ℹ️  Swap creation skipped: system has {{ common_total_ram_mb }} MB RAM (≥ 2GB)"
  when: common_total_ram_mb | int >= 2048
  tags: [common, swap]

- name: Configure firewall (UFW)
  tags: [common, firewall]
  block:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Allow Grafana
      community.general.ufw:
        rule: allow
        port: "3000"
        proto: tcp
      when: grafana_enabled | default(false)

    - name: Reload UFW
      community.general.ufw:
        state: reloaded

- name: Verify firewall status
  ansible.builtin.command: ufw status
  register: common_firewall_status
  changed_when: false
  tags: [common, firewall]

- name: Create application directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - "{{ app_deploy_path }}"
    - "{{ app_deploy_path }}/logs"
  tags: [common, directories]

- name: Display common role completion
  ansible.builtin.debug:
    msg: |
      ✅ Common role completed:
      - System packages updated
      - Timezone: {{ vps_timezone }}
      - Locale: {{ vps_locale }}
      - Firewall configured (22, 80, 443)
      - Directories created: {{ app_deploy_path }}
      - Swap: {{ 'configured' if not common_swap_file.stat.exists else 'already exists' }}
  tags: [common]
