---
# =============================================================================
# GLOBAL VARIABLES - Memocards Deployment
# Global variables for application deployment
# =============================================================================

# =============================================================================
# VPS CONFIGURATION
# Note: VPS IP and user are defined in inventory/hosts.yml via ansible_host and ansible_user
# Access via: {{ hostvars[inventory_hostname]['ansible_host'] }} or {{ ansible_user }}
# =============================================================================
vps_timezone: "Europe/Moscow"
vps_locale: "en_US.UTF-8"

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
domain: "memocards.duckdns.org"
# Default image (can be overridden with --extra-vars "app_image=...")
# Examples:
#   app_image: "ghcr.io/apolenkov/memocards:latest"        # Latest version
#   app_image: "ghcr.io/apolenkov/memocards:0.1"           # Specific version
#   app_image: "ghcr.io/apolenkov/memocards:abc1234"       # Specific commit
app_image: "ghcr.io/apolenkov/memocards:latest"
app_port: 8080
app_deploy_path: "/opt/memocards"

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
db_name: "memocards"
db_user: "memocards_user"
# db_password stored in secrets.yml (vault)

# =============================================================================
# SSL CONFIGURATION
# =============================================================================
ssl_email: "apolenkov@gmail.com"
# duckdns_token stored in secrets.yml (vault)

# =============================================================================
# DOCKER CONFIGURATION
# =============================================================================
docker_compose_version: "v2.24.0"
docker_install_method: "repository"

# =============================================================================
# GITHUB CONFIGURATION (for private GHCR)
# =============================================================================
github_actor: "apolenkov"
# github_token stored in secrets.yml (vault)

# =============================================================================
# RESOURCE LIMITS (for VPS with 2GB RAM)
# =============================================================================
app_memory_limit: "1500m"
postgres_memory_limit: "512m"
postgres_shared_buffers: "256MB"
postgres_effective_cache_size: "512MB"

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================
# Grafana settings
grafana_enabled: true
grafana_port: 127.0.0.1:3000
grafana_admin_user: "admin"
# grafana_admin_password stored in secrets.yml (vault)

# Prometheus settings
prometheus_enabled: true
prometheus_port: 127.0.0.1:9090

# Loki settings
loki_enabled: true
loki_port: 127.0.0.1:3100

# Promtail settings
promtail_enabled: true

# Monitoring container names
prometheus_container_name: "memocards-prometheus-prod"
grafana_container_name: "memocards-grafana-prod"
loki_container_name: "memocards-loki-prod"
promtail_container_name: "memocards-promtail-prod"

# =============================================================================
# FIREWALL CONFIGURATION
# =============================================================================
# Note: Monitoring ports (3000, 9090) are NOT exposed to internet
# Access via localhost only for security
firewall_allowed_ports:
  - "22" # SSH
  - "80" # HTTP
  - "443" # HTTPS

# =============================================================================
# MANAGEMENT CONFIGURATION
# =============================================================================
# Backup and monitoring removed for MVP
# Using Docker restart policy instead of cron monitoring
