---
# =============================================================================
# GLOBAL VARIABLES - Memocards Deployment
# Глобальные переменные для развертывания приложения
# =============================================================================

# =============================================================================
# VPS CONFIGURATION
# =============================================================================
vps_ip: "185.239.48.55"
vps_user: "root"
vps_timezone: "Europe/Moscow"
vps_locale: "en_US.UTF-8"

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
domain: "memocards.duckdns.org"
# Default image (can be overridden with --extra-vars "app_image=...")
# Examples:
#   app_image: "ghcr.io/apolenkov/memocards:latest"        # Latest version
#   app_image: "ghcr.io/apolenkov/memocards:0.1"           # Specific version
#   app_image: "ghcr.io/apolenkov/memocards:abc1234"       # Specific commit
app_image: "ghcr.io/apolenkov/memocards:latest"
app_port: 8080
app_deploy_path: "/opt/memocards"

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
db_name: "memocards"
db_user: "memocards_user"
# db_password хранится в secrets.yml (vault)

# =============================================================================
# SSL CONFIGURATION
# =============================================================================
ssl_email: "apolenkov@gmail.com"
# duckdns_token хранится в secrets.yml (vault)

# =============================================================================
# DOCKER CONFIGURATION
# =============================================================================
docker_compose_version: "v2.24.0"
docker_install_method: "repository"

# =============================================================================
# GITHUB CONFIGURATION (для приватного GHCR)
# =============================================================================
github_actor: "apolenkov"
# github_token хранится в secrets.yml (vault)

# =============================================================================
# RESOURCE LIMITS (для VPS с 2GB RAM)
# =============================================================================
app_memory_limit: "1500m"
postgres_memory_limit: "512m"
postgres_shared_buffers: "256MB"
postgres_effective_cache_size: "512MB"

# =============================================================================
# FIREWALL CONFIGURATION
# =============================================================================
firewall_allowed_ports:
  - "22"   # SSH
  - "80"   # HTTP
  - "443"  # HTTPS

# =============================================================================
# BACKUP CONFIGURATION
# =============================================================================
backup_enabled: true
backup_schedule: "0 2 * * *"  # Ежедневно в 2:00
backup_retention_days: 7

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================
monitoring_enabled: true
monitoring_schedule: "*/5 * * * *"  # Каждые 5 минут

