version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    reviewers:
      - "apolenkov"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    groups:
      # Group patch and minor updates together
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      # Security updates always separate
      security:
        patterns:
          - "*"
        update-types:
          - "security"

  # npm packages (Vaadin frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    reviewers:
      - "apolenkov"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "build(deps-npm)"
      include: "scope"
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    reviewers:
      - "apolenkov"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"

