---
version: 2
updates:
  # Gradle (Java dependencies) - ALL IN ONE PR
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group ALL Gradle dependencies into 1 PR
    groups:
      all-gradle:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # npm (Frontend dependencies) - ALL IN ONE PR
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group ALL npm dependencies into 1 PR
    groups:
      all-npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions - ALL IN ONE PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "ci"
      include: "scope"
    
    # Group ALL GitHub Actions into 1 PR
    groups:
      all-actions:
        patterns:
          - "*"

  # Docker - ALL IN ONE PR
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "docker"
      include: "scope"
    # Ignore our own app image (built by Jib)
    ignore:
      - dependency-name: "ghcr.io/apolenkov/memocards"
    
    # Group ALL Docker images into 1 PR
    groups:
      all-docker:
        patterns:
          - "*"
