---
version: 2
updates:
  # Gradle (Java dependencies) - ALL IN ONE PR
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group ALL Gradle dependencies into 1 PR
    groups:
      all-gradle:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # npm (Frontend dependencies) - ALL IN ONE PR
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group ALL npm dependencies into 1 PR
    groups:
      all-npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions - ALL IN ONE PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1  # Only 1 PR at a time
    reviewers:
      - "apolenkov"
    assignees:
      - "apolenkov"
    commit-message:
      prefix: "ci"
      include: "scope"
    
    # Group ALL GitHub Actions into 1 PR
    groups:
      all-actions:
        patterns:
          - "*"

  # NOTE: Docker ecosystem disabled because:
  # - We use Jib for building images (no Dockerfile)
  # - Base images (postgres) are updated manually when needed
  # - Dependabot can't find Dockerfile and fails
