---
name: Run Code Quality Checks
description: Runs Spotless, Checkstyle, SpotBugs, SonarLint, and CSS linting

inputs:
  gradle-opts:
    description: "Gradle JVM options"
    required: false
    default: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

runs:
  using: composite
  steps:
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run Spotless check
      shell: bash
      env:
        GRADLE_OPTS: ${{ inputs.gradle-opts }}
      run: ./gradlew spotlessCheck

    - name: Run Checkstyle
      shell: bash
      env:
        GRADLE_OPTS: ${{ inputs.gradle-opts }}
      run: ./gradlew checkstyleMain checkstyleTest

    - name: Run SpotBugs
      shell: bash
      env:
        GRADLE_OPTS: ${{ inputs.gradle-opts }}
      run: ./gradlew spotbugsMain spotbugsTest

    - name: Run SonarLint
      shell: bash
      env:
        GRADLE_OPTS: ${{ inputs.gradle-opts }}
      run: ./gradlew sonarlintMain sonarlintTest

    - name: Run CSS linting
      shell: bash
      env:
        GRADLE_OPTS: ${{ inputs.gradle-opts }}
      run: ./gradlew lintCss
