services:
  postgres:
    image: postgres:15-alpine
    container_name: memocards-postgres
    environment:
      POSTGRES_DB: memocards
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Application service (optional - use with --profile full-stack)
  # Uncomment 'image' line to use published image from ghcr.io
  # Or uncomment 'build' section to build locally
  app:
    # Use published image:
    # image: ghcr.io/apolenkov/memocards:latest
    
    # Or build locally:
    build:
      context: .
      dockerfile: Dockerfile.local
    
    container_name: memocards-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      DB_URL: jdbc:postgresql://postgres:5432/memocards
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JAVA_OPTS: ${JAVA_OPTS:--XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    profiles:
      - full-stack

volumes:
  postgres_data:
    driver: local
