services:
  postgres:
    image: postgres:15-alpine
    container_name: memocards-postgres
    environment:
      POSTGRES_DB: memocards
      POSTGRES_USER: ${DB_USER:-memocards_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Application
  app:
    image: ${APP_IMAGE:-ghcr.io/apolenkov/memocards:latest}
    container_name: memocards-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Override Vaadin settings for containers
      VAADIN_LAUNCH_BROWSER: false
      VAADIN_PRODUCTION_MODE: true
      # Override database URL for containers (required for Docker networking)
      DB_URL: jdbc:postgresql://postgres:5432/memocards
    volumes:
      # Mount logs directory to container
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
