[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -jar /app/application.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
# Spring Configuration
SPRING_PROFILES_ACTIVE = "prod"
VAADIN_PRODUCTION_MODE = "true"
VAADIN_LAUNCH_BROWSER = "false"

# Cache Settings (production-optimized)
CACHE_PAGINATION_COUNT_TTL = "300000"  # 5 minutes
CACHE_MONITORING_ENABLED = "true"

# Security
MAX_FAILED_ATTEMPTS = "5"
SEED_DEMO_DATA = "false"  # Disable in production

# Server Configuration
SERVER_PORT = "8080"
SERVER_COMPRESSION_ENABLED = "true"
SERVER_COMPRESSION_MIN_SIZE = "512"
SERVER_HTTP2_ENABLED = "true"

# Management Configuration
MANAGEMENT_ENDPOINTS = "health,info,metrics,prometheus"
MANAGEMENT_HEALTH_SHOW_DETAILS = "when-authorized"
MANAGEMENT_HEALTH_SHOW_COMPONENTS = "when-authorized"
MANAGEMENT_METRICS_JVM = "true"
MANAGEMENT_METRICS_JDBC = "true"
MANAGEMENT_METRICS_HIKARI = "true"
MANAGEMENT_METRICS_LOGBACK = "true"
MANAGEMENT_PROMETHEUS_ENABLED = "true"

# Monitoring
SLOW_QUERY_THRESHOLD = "100"
HIKARI_MONITORING_ENABLED = "true"
HIKARI_LOG_INTERVAL = "60000"
CACHE_LOG_INTERVAL = "300000"  # 5 minutes

# UI Configuration
SEARCH_DEBOUNCE_MS = "300"
PAGINATION_PAGE_SIZE = "50"
