spring:
  application:
    name: flashcards
  profiles:
    active: dev

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
        default_batch_fetch_size: 16
        max_fetch_depth: 3
        query:
          plan_cache_max_size: 2048
          plan_cache_parameter_metadata_max_size: 128
        session:
          events_log: false
        enable_lazy_load_no_trans: false
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
        default_batch_fetch_size: 32
        max_fetch_depth: 2
        query:
          plan_cache_max_size: 4096
          plan_cache_parameter_metadata_max_size: 256
        session:
          events_log: false
        enable_lazy_load_no_trans: false
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: true
        default_batch_fetch_size: 16
        max_fetch_depth: 3
        query:
          plan_cache_max_size: 2048
          plan_cache_parameter_metadata_max_size: 128
        session:
          events_log: false
        enable_lazy_load_no_trans: false
  flyway:
    enabled: true
    locations: classpath:db/migration


