spring:
  application:
    name: flashcards
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 10000      # Fast failover (10s)
      validation-timeout: 3000       # Quick connection validation
      leak-detection-threshold: 60000  # Detect leaks after 60s
      idle-timeout: 300000
      max-lifetime: 1800000
      pool-name: FlashcardsHikariPool
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application
  launch-browser: false  # Override in dev profile
  productionMode: true # Override in dev profile

# Server configuration
server:
  compression:
    enabled: true
    min-response-size: 512
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
      - image/svg+xml
      - application/xml
  http2:
    enabled: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    enable:
      jvm: true
      jdbc: true
      hikaricp: true
      logback: true
  prometheus:
    metrics:
      export:
        enabled: true

app:
  cache:
    user:
      ttl-minutes: ${CACHE_USER_TTL:30}
      max-size: ${CACHE_USER_MAX_SIZE:1000}
    decks:
      ttl-ms: ${CACHE_DECKS_TTL:60000}  # 1 minute (UI-scoped cache)
      max-size: ${CACHE_DECKS_MAX_SIZE:1000}
    known-cards:
      ttl-ms: ${CACHE_KNOWN_CARDS_TTL:300000}  # 5 minutes (less volatile than decks)
      max-size: ${CACHE_KNOWN_CARDS_MAX_SIZE:1000}
    pagination-count:
      ttl-ms: ${CACHE_PAGINATION_COUNT_TTL:60000}  # 1 minute (dev/test default, prod uses 5 minutes)
      max-size: ${CACHE_PAGINATION_COUNT_MAX_SIZE:500}
  ui:
    search:
      debounce-ms: ${SEARCH_DEBOUNCE_MS:300}  # Debouncing timeout for search fields
    pagination:
      page-size: ${PAGINATION_PAGE_SIZE:50}  # Number of items per page in lists
  monitoring:
    slow-query-threshold-ms: ${SLOW_QUERY_THRESHOLD:100}
    hikari:
      enabled: ${HIKARI_MONITORING_ENABLED:true}
      log-interval-ms: ${HIKARI_LOG_INTERVAL:60000}
    cache:
      enabled: ${CACHE_MONITORING_ENABLED:false}  # Disabled by default (enable for debugging)
      log-interval-ms: ${CACHE_LOG_INTERVAL:300000}  # 5 minutes
  security:
    max-failed-attempts: ${MAX_FAILED_ATTEMPTS:5}
    failed-attempts-window-minutes: ${FAILED_ATTEMPTS_WINDOW:15}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

vaadin:
  launch-browser: false
  productionMode: false

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.apolenkov.application: DEBUG

# Data seeding configuration (dev profile only)
app:
  seed:
    demo:
      enabled: ${SEED_DEMO_DATA:true}
      admin-password: ${DEMO_ADMIN_PASSWORD:admin}
      user-password: ${DEMO_USER_PASSWORD:user}
    test:
      enabled: ${GENERATE_TEST_DATA:false}
      test-user-password: ${TEST_USER_PASSWORD:testPassword123}
      batch:
        users: ${BATCH_SIZE_USERS:100}
      limits:
        users: ${LIMIT_USERS:100}
        decks-per-user: ${LIMIT_DECKS:10}
        cards-per-deck: ${LIMIT_CARDS:50}
        news: ${LIMIT_NEWS:50}

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    org.springframework.jdbc.core: INFO
    org.apolenkov.application: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org.springframework: WARN
    org.springframework.jdbc.core: INFO
    org.springframework.boot: INFO
    org.apolenkov.application: INFO
    org.apolenkov.application.audit: INFO
    org.atmosphere: WARN
    org.flywaydb: INFO
    com.vaadin: WARN
    com.zaxxer.hikari: INFO

# Production cache optimization: longer TTL with event-driven invalidation
app:
  cache:
    pagination-count:
      ttl-ms: 300000  # 5 minutes (longer TTL safe with event-driven invalidation)
    known-cards:
      ttl-ms: 600000  # 10 minutes (less volatile, event-driven invalidation ensures freshness)

