spring:
  application:
    name: flashcards
  profiles:
    active: dev

# Logging configuration
logging:
  level:
    org.apolenkov.application: INFO
    org.springframework.security: INFO
    com.vaadin: WARN
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    # Suppress Tomcat session loading errors
    "org.apache.catalina.session.StandardManager": WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application

# Server configuration
server:
  servlet:
    session:
      # Disable persistent session storage to avoid loading errors
      persistent: false
      # Session timeout in minutes (30 minutes)
      timeout: 30m
  # Tomcat configuration
  tomcat:
    threads:
      max: 200
      min-spare: 10

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # PostgreSQL optimizations
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
      pool-name: "FlashcardsHikariCP"
  flyway:
    enabled: true
    locations: classpath:db/migration

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # PostgreSQL optimizations
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
      pool-name: "FlashcardsHikariCP"
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
    level:
      org.springframework.jdbc: WARN
      org.springframework.jdbc.core.JdbcTemplate: WARN