spring:
  application:
    name: flashcards
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  # Database configuration (общая для всех профилей)
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application

# Actuator endpoints (базовая конфигурация для production)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized

---
# Development Profile (только отличия от базовой конфигурации)
spring:
  config:
    activate:
      on-profile: dev

# Demo user configuration (development only)
demo:
  admin:
    password: ${DEMO_ADMIN_PASSWORD}
  user:
    password: ${DEMO_USER_PASSWORD}

vaadin:
  launch-browser: true

# Dev: больше endpoints для отладки
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

---
# Production Profile (только отличия от базовой конфигурации)
spring:
  config:
    activate:
      on-profile: prod

vaadin:
  launch-browser: false
