spring:
  application:
    name: flashcards
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      pool-name: FlashcardsHikariPool
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application

# Server configuration
server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/css,application/javascript,application/json

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized

app:
  cache:
    user:
      ttl-minutes: ${CACHE_USER_TTL:30}
      max-size: ${CACHE_USER_MAX_SIZE:1000}

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

# Data seeding configuration (dev profile only)
app:
  seed:
    demo:
      enabled: ${SEED_DEMO_DATA:true}
      admin-password: ${DEMO_ADMIN_PASSWORD:admin}
      user-password: ${DEMO_USER_PASSWORD:user}
    test:
      enabled: ${GENERATE_TEST_DATA:false}
      test-user-password: ${TEST_USER_PASSWORD:testPassword123}
      batch:
        users: ${BATCH_SIZE_USERS:100}
      limits:
        users: ${LIMIT_USERS:100}
        decks-per-user: ${LIMIT_DECKS:10}
        cards-per-deck: ${LIMIT_CARDS:50}
        news: ${LIMIT_NEWS:50}

vaadin:
  launch-browser: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.apolenkov.application: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

# Data seeding configuration (test profile)
app:
  seed:
    demo:
      enabled: ${SEED_DEMO_DATA:false}
      admin-password: ${DEMO_ADMIN_PASSWORD:admin}
      user-password: ${DEMO_USER_PASSWORD:user}
    test:
      enabled: ${GENERATE_TEST_DATA:false}
      test-user-password: ${TEST_USER_PASSWORD:testPassword123}
      batch:
        users: ${BATCH_SIZE_USERS:50}
      limits:
        users: ${LIMIT_USERS:50}
        decks-per-user: ${LIMIT_DECKS:5}
        cards-per-deck: ${LIMIT_CARDS:20}
        news: ${LIMIT_NEWS:10}

vaadin:
  launch-browser: false

logging:
  level:
    org.springframework.jdbc.core: INFO
    org.apolenkov.application: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

vaadin:
  launch-browser: false
