spring:
  application:
    name: flashcards
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS

# Logging configuration - levels defined in logback-spring.xml
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{60} [%X{requestId:-}] [%X{userId:-}] - %msg%n"

vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,org.apolenkov.application

# Basic actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Server configuration
server:
  servlet:
    session:
      persistent: false
      timeout: 30m
  tomcat:
    threads:
      max: 200
      min-spare: 10

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  # Basic configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
      pool-name: "FlashcardsHikariCP"
  flyway:
    enabled: true
    locations: classpath:db/migration

# Demo user configuration (development only)
demo:
  admin:
    password: admin
  user:
    password: user

vaadin:
  launch-browser: true

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
      pool-name: "FlashcardsHikariCP"
  flyway:
    enabled: true
    locations: classpath:db/migration
