# EntryPoints - Internal routing entrypoint
# Nginx on host handles 80/443 (external traffic, SSL termination)
entryPoints:
  web:
    address: ":8080"
    # Main entrypoint for internal routing (Nginx proxies all traffic here)
  traefik:
    address: ":8082"
    # Internal API/dashboard entrypoint (mapped to host:8081 via docker-compose for direct access)

api:
  dashboard: true
  insecure: true  # Required for subpath access via Nginx (auth handled by Nginx basic auth)
  debug: true
  # Dashboard accessible via Nginx at /traefik/
  # Note: insecure: true allows access without direct auth
  # Nginx basic auth middleware protects access
  # API is automatically available on the "traefik" entryPoint

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: memocards-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog: {}

# Certificate resolver not needed - Nginx handles SSL on host
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: ${ACME_EMAIL:-apolenkov@gmail.com}
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web

