---
# =============================================================================
# ROLE: docker
# Установка Docker Engine и Docker Compose v2
# =============================================================================

- name: Remove old Docker versions if present
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  tags: [docker, install]

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  tags: [docker, install]

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: [docker, install]

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  tags: [docker, install]

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: docker_system_arch
  changed_when: false
  tags: [docker, install]

- name: Get Ubuntu codename
  ansible.builtin.command: lsb_release -cs
  register: docker_ubuntu_codename
  changed_when: false
  tags: [docker, install]

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker_system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ docker_ubuntu_codename.stdout }} stable
    state: present
    filename: docker
    update_cache: true
  tags: [docker, install]

- name: Install Docker Engine and plugins
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: [docker, install]

- name: Configure Docker daemon
  ansible.builtin.copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2",
        "live-restore": true,
        "userland-proxy": false,
        "default-ulimits": {
          "nofile": {
            "Name": "nofile",
            "Hard": 64000,
            "Soft": 64000
          }
        }
      }
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: Restart docker
  tags: [docker, config]

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  tags: [docker, service]

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  tags: [docker, config]

- name: Wait for Docker to be ready
  ansible.builtin.command: docker info
  register: docker_docker_info
  retries: 5
  delay: 3
  until: docker_docker_info.rc == 0
  changed_when: false
  tags: [docker, service]

- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
  tags: [docker, ghcr]

- name: Install Python dependencies for Docker module
  ansible.builtin.pip:
    name:
      - requests
      - docker
    state: present
  tags: [docker, ghcr]

- name: Login to GitHub Container Registry
  community.docker.docker_login:
    registry: ghcr.io
    username: "{{ github_actor }}"
    password: "{{ vault_github_token }}"
    reauthorize: true
  when: vault_github_token is defined and vault_github_token != ""
  tags: [docker, ghcr]

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version_output
  changed_when: false
  tags: [docker, verify]

- name: Verify Docker Compose installation
  ansible.builtin.command: docker compose version
  register: docker_compose_version_output
  changed_when: false
  tags: [docker, verify]

- name: Display Docker role completion
  ansible.builtin.debug:
    msg: |
      ✅ Docker role completed:
      - Docker Engine: {{ docker_version_output.stdout }}
      - Docker Compose: {{ docker_compose_version_output.stdout }}
      - Docker service: running and enabled
      - User {{ ansible_user }} added to docker group
      - GHCR login: {{ 'configured' if (vault_github_token is defined and vault_github_token != '') else 'skipped (no token)' }}
  tags: [docker]
