---
name: Pull Request Validation

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
# Allow only one concurrent PR validation per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  # Build Configuration
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"
  TESTCONTAINERS_REUSE_ENABLE: "true"

  # Artifact retention (days) - shorter for PRs
  ARTIFACT_RETENTION_DAYS: 7

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Linters and static analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Run code quality checks
        uses: ./.github/actions/code-quality
        with:
          gradle-opts: ${{ env.GRADLE_OPTS }}

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Unit test execution

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests
        with:
          gradle-opts: ${{ env.GRADLE_OPTS }}
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 12 # TestContainers + integration tests

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Run integration tests
        uses: ./.github/actions/run-integration-tests
        with:
          gradle-opts: ${{ env.GRADLE_OPTS }}
          testcontainers-reuse: ${{ env.TESTCONTAINERS_REUSE_ENABLE }}
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
